/* 
 * Multrees WebAPI
 *
 * Disruption Open Breakthrough Gamechanger Innovative Millennial Leverage Next Generation Platform Legacy Digital Democratisation Anything … as-a-service Marketplace 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// An account.
type Account struct {

	CustomerId string `json:"customerId"`

	AccountName string `json:"accountName"`
}
