/* 
 * Multrees WebAPI
 *
 * Disruption Open Breakthrough Gamechanger Innovative Millennial Leverage Next Generation Platform Legacy Digital Democratisation Anything … as-a-service Marketplace 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// A payment ... [TODO]
type Payment struct {

	CustomerId string `json:"customerId"`

	AccountName string `json:"accountName"`

	// If this is an advanced notice then this is the settlement date. Otherwise it is the date of the payment. 
	Notice time.Time `json:"notice,omitempty"`

	// If this is a regular payment then describe the repeat.
	Repeat string `json:"repeat,omitempty"`
}
